@IdentityService_HostAddress = http://localhost:5101

###
# Register a new user
# Endpoint successfully creates a new user and returns the user details.
POST {{IdentityService_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Username": "Marcos004",
  "email": "marcos004@pag.com",
  "password": "12345678"
}

###
# Register the same user again
# Endpoint returns a 400 Bad Request error indicating the user already exists.
POST {{IdentityService_HostAddress}}/api/auth/register 
Content-Type : application/json
{
  "Username": "John Doe",
  "email": "marcos001@pag.com",
  "password": "12345678"
}

###
# 3. Login with Correct Credentials
# This endpoint should succeed and return a JWT token.

POST {{IdentityService_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "UsernameOrEmail": "Marcos",
  "Password": "12345678"
}


###
# # 4. Login with Incorrect Password
# # This endpoint should fail.

# POST {{IdentityService_HostAddress}}/api/auth/login
# Content-Type: application/json

# {
#   "email": "test@example.com",
#   "password": "WrongPassword"
# }
