@PagarteAPI_HostAddress = http://localhost:5102

POST {{PagarteAPI_HostAddress}}/api/payments/create-payment-method/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkwOTZEN0I5MkMyRjA4Q0M5ODgwNzMzODNBNzI1RkVDMkJCMDU4Q0YiLCJ4NXQiOiJrSmJYdVN3dkNNeVlnSE00T25KZjdDdXdXTTgiLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MTExLyIsImV4cCI6MTc1MTkyNTE1NywiaWF0IjoxNzUxOTIzMzU3LCJhdWQiOiJwYXltZW50c19hcGkiLCJzY29wZSI6Im9mZmxpbmVfYWNjZXNzIHByb2ZpbGUgYXBpIiwianRpIjoiNzU4NzdkNzktOTEzMi00NWQ3LTlmYjAtM2ExZGUwNDhiYmQ1Iiwic3ViIjoiNDEzMTk3NTctNDM5Ni00ZGMyLWI1YTItNzdlYTVkYjg5Y2QyIiwiZW1haWwiOiJtYXJjb3NAcGFnLmNvbSIsIm5hbWUiOiJNYXJjb3MiLCJvaV9hdV9pZCI6ImQxMDMzZjRjLTY1MmMtNDA0Ny04ZTFlLWNlNDFkOGRkMzM1NSIsIm9pX3Rrbl9pZCI6ImZlZmQ5ZGViLTkxODItNDQzMS05MjI5LTc5NmE3MzAxYmJmMSJ9.n9wb0Faw-IxTHuOnIGPmTR7AaN18xcUxbjZJVnqYjZltjCmiTFv6bO2_zZS_69onxwYRs1nv3GYcIdtJMB6zS34VAz8N3IIZR0aW1zqkoF9K2REi8wKTsEsh8iyC7sFiePVveS5UNyfznWK7uUwfKYoewgwl6upFD2zS5Iv5p6UmmRM68pfB-f65gTPCxaumrxQMu6wEsiI-WROt5iPHqjdOUXVIuDljjNsvFj6zhckMJIlljMjfL0HTYa84nfHylc2dktJwxfT409x9E3JjH_tkCByDthqdx95dqJ18Psm5E22XLReuJTDpFNOgqcl8-70VpV37p6Z-N7PSC6oP8g
Content-Type: application/json
{
  "paymentMethodType": "Visa",
  "cardNumber": "1111111111111111",
  "cardHolderName": "John Doe",
  "expirationMonth": 12,
  "expirationYear": 2025,
  "cvv": "123"
}

###

@PagarteAPI_HostAddress = http://localhost:5102

GET {{PagarteAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

