@PagarteAPI_HostAddress = http://localhost:5102

POST {{PagarteAPI_HostAddress}}/api/payments/create-payment-method/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkwOTZEN0I5MkMyRjA4Q0M5ODgwNzMzODNBNzI1RkVDMkJCMDU4Q0YiLCJ4NXQiOiJrSmJYdVN3dkNNeVlnSE00T25KZjdDdXdXTTgiLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MTExLyIsImV4cCI6MTc1MTg2ODE2OCwiaWF0IjoxNzUxODY2MzY4LCJhdWQiOiJwYXltZW50c19hcGkiLCJzY29wZSI6Im9mZmxpbmVfYWNjZXNzIHByb2ZpbGUgYXBpIiwianRpIjoiMDk3ZDEzZmEtZGVlNS00NGM1LTljNGEtYWQyZDcxM2E0NzYxIiwic3ViIjoiNDEzMTk3NTctNDM5Ni00ZGMyLWI1YTItNzdlYTVkYjg5Y2QyIiwiZW1haWwiOiJtYXJjb3NAcGFnLmNvbSIsIm5hbWUiOiJNYXJjb3MiLCJvaV9hdV9pZCI6IjE4MDJkZTg0LTlmZGItNDIzZS04NmRjLWIwNDU4OTYzZWIxNiIsIm9pX3Rrbl9pZCI6IjI0NjdjMTU5LTExMzMtNGUxZi1iNWI5LTU2ZDkyZTQ5MzVhMyJ9.ZrV0Ktq7Fy9k8RnaQrQzDOtPD_dTFc_Syr0rIhrE9UrGrtgKl9DdVL-ZunkMgwcheqdPYWMxeDF66M0n6_LpnGfyScRALI-Wh8NK86wSeL1447mYFSB4FcNWPhCz927kA3GvYfloFyjnoidvKfHX4V3g8b8x-0co-IuImuDv-twOdkF4SpmOikgVeQ-fOUBr30A4U9V0NZzz743KR8Ktpw4PM6xJuGlLjg8ifsiYMPUY8LosijNcoM_paRh1XEj32ZLTCviyokMFwuZwgoYGSGHDinmAmMi0ukLtfOQF8CBuC6eBMW_L-7bh-HI4giUa8hqR3Rig-VZTfG3j48ltfw
Content-Type: application/json
{
  "paymentMethodType": "Visa",
  "cardNumber": "1111111111111111",
  "cardHolderName": "John Doe",
  "expirationMonth": 12,
  "expirationYear": 2025,
  "cvv": "123"
}

###

@PagarteAPI_HostAddress = http://localhost:5102

GET {{PagarteAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

